"""Lineage round-trip against real ClickHouse (spec §6.14 / §8.4, CONTRACTS §1).

The one assertion that matters here is the last one in `_check_event`: every span, sliced out of
the raw line **by byte offsets**, equals the value it claims to map to. A previous bug survived a
long time because nobody checked it — the offsets looked plausible and the UI highlighted
something, just not the right bytes. Python `len()` counts characters, so the slice is done on
`raw.encode()`; a character-offset regression fails here the moment any line contains a non-ASCII
byte, and the ordering/coverage checks below catch it even on pure ASCII.

The whole module skips (never fails) when ClickHouse is not up, so `make check` still works on a
bare checkout. Nothing here hardcodes a row count, a source name or an event_uid: the table is
sampled and only invariants are asserted, because the corpus is regenerated by the demo.
"""

from __future__ import annotations

import hashlib
from typing import Any

import pytest

pytestmark = pytest.mark.usefixtures("clickhouse")

# Enough rows to cross every shipped pack without making the suite slow.
SAMPLE_LIMIT = 40


def _events(client: Any, **params: Any) -> dict[str, Any]:
    r = client.get("/api/v1/events", params=params)
    assert r.status_code == 200, r.text
    return r.json()


def _lineage(client: Any, event_uid: str) -> dict[str, Any]:
    r = client.get(f"/api/v1/events/{event_uid}/lineage")
    assert r.status_code == 200, r.text
    return r.json()


def _check_event(lin: dict[str, Any]) -> None:
    """Every invariant a single lineage response must satisfy."""
    uid = lin["event_uid"]
    raw_bytes = lin["raw"].encode("utf-8")

    # `verified` is a claim about bytes, so prove it independently of the API.
    assert lin["verified"] is True, f"{uid} did not verify"
    assert hashlib.sha256(raw_bytes).hexdigest().lower() == lin["raw_sha256"].lower(), uid

    if lin["storage_mode"] != "template":
        # Quarantined lines are stored whole: no template, so no spans to show.
        assert lin["tokens"] == [] and lin["spans"] == {}
        return

    vars_ = lin["vars"]
    spans = lin["spans"]
    assert len(spans) == len(vars_), f"{uid}: {len(spans)} spans for {len(vars_)} vars"

    # Walk the tokens exactly as the frontend does: literals advance the cursor, slots consume
    # one var each, and the span recorded for that slot must be those bytes.
    cursor, i = 0, 0
    for tok in lin["tokens"]:
        if not tok.get("slot"):
            cursor += len(tok.get("lit", "").encode("utf-8"))
            continue
        value = vars_[i]
        i += 1
        span = spans[tok["slot"]]

        assert isinstance(span, list) and len(span) == 2, f"{uid}: span is not a [start, end] pair"
        assert all(isinstance(n, int) for n in span), f"{uid}: span offsets must be ints"
        start, end = span
        assert 0 <= start <= end <= len(raw_bytes), f"{uid}: span {span} outside the raw line"
        assert start == cursor, f"{uid}: {tok['slot']} starts at {start}, expected {cursor}"
        assert end - start == len(value.encode("utf-8")), f"{uid}: {tok['slot']} wrong length"

        # THE assertion: the bytes under the span are the value the UI will attribute to them.
        assert raw_bytes[start:end].decode("utf-8") == value, (
            f"{uid}: span {span} for slot {tok['slot']!r} holds "
            f"{raw_bytes[start:end]!r}, not {value!r}")
        cursor = end

    assert i == len(vars_), f"{uid}: {i} slots consumed {len(vars_)} vars"
    # Literals plus vars in token order must reproduce the line (CONTRACTS §1).
    assert cursor == len(raw_bytes) or lin["tokens"][-1].get("lit"), uid

    # Every mapped OCSF path must resolve to a slot that actually has bytes, or clicking the
    # field in the UI dead-ends.
    assert set(lin["field_map"].values()) <= set(spans), f"{uid}: field_map points at no span"


def test_events_endpoint_returns_the_contract_shape(client: Any) -> None:
    page = _events(client, limit=5)
    assert set(page) == {"events", "total", "sources", "classes"}
    assert isinstance(page["total"], int) and page["total"] >= 0
    assert all(set(c) == {"class_uid", "name"} for c in page["classes"])
    if not page["events"]:
        pytest.skip("aletheia.events is empty — run the traffic scenario first")
    for ev in page["events"]:
        # CONTRACTS §5 invariants, checked on whatever happens to be stored.
        assert ev["type_uid"] == ev["class_uid"] * 100 + ev["activity_id"]
        assert ev["category_uid"] == {4001: 4, 4002: 4, 4003: 4, 3002: 3, 2004: 2}.get(
            ev["class_uid"], 0)
        assert isinstance(ev["time"], int)
        assert set(ev["aletheia"]) >= {
            "event_uid", "source_id", "parse_status", "storage_mode", "template_id", "pack",
            "pack_version", "raw_sha256", "verified", "merkle_batch"}
        assert ev["aletheia"]["parse_status"] in {"full", "partial", "raw_only"}
        assert ev["aletheia"]["storage_mode"] in {"template", "verbatim"}
        assert all(isinstance(v, str) for v in ev["unmapped"].values())


def test_every_span_slices_back_to_its_own_value(client: Any) -> None:
    """The product's central claim, checked on whatever rows are in the table right now."""
    page = _events(client, limit=SAMPLE_LIMIT)
    if not page["events"]:
        pytest.skip("aletheia.events is empty — run the traffic scenario first")
    for ev in page["events"]:
        _check_event(_lineage(client, ev["aletheia"]["event_uid"]))


def test_lineage_holds_for_every_source_present(client: Any) -> None:
    """Spread across sources so each shipped pack's envelope splice is exercised, not just one."""
    page = _events(client, limit=1)
    sources = page["sources"]
    if not sources:
        pytest.skip("no sources in aletheia.events yet")
    checked = 0
    for source_id in sources:
        for ev in _events(client, source_id=source_id, limit=8)["events"]:
            lin = _lineage(client, ev["aletheia"]["event_uid"])
            # Studio-approved packs live in the live repo; this process has an empty one.
            if lin["storage_mode"] == "template" and not lin["pack"]:
                continue
            _check_event(lin)
            checked += 1
    if not checked:
        pytest.skip("only Studio-approved packs present; none resolvable from this process")


def test_reconstructed_raw_matches_the_stored_hash(client: Any) -> None:
    """`verified` must never be asserted without the hash being recomputed (CONTRACTS §10.1)."""
    page = _events(client, limit=SAMPLE_LIMIT)
    if not page["events"]:
        pytest.skip("aletheia.events is empty")
    for ev in page["events"]:
        lin = _lineage(client, ev["aletheia"]["event_uid"])
        assert lin["raw_sha256"], "an event with no recorded hash cannot be verified honestly"
        assert hashlib.sha256(lin["raw"].encode()).hexdigest().lower() == \
            lin["raw_sha256"].lower()
        assert lin["event"]["aletheia"]["verified"] == lin["verified"]


def test_spans_are_recomputed_not_stored(client: Any) -> None:
    """Two calls must agree exactly; spans come from the tokens every time (spec §8.4)."""
    page = _events(client, limit=1)
    if not page["events"]:
        pytest.skip("aletheia.events is empty")
    uid = page["events"][0]["aletheia"]["event_uid"]
    assert _lineage(client, uid)["spans"] == _lineage(client, uid)["spans"]


def test_unknown_event_is_a_404(client: Any) -> None:
    r = client.get("/api/v1/events/NOT_A_REAL_EVENT_UID/lineage")
    assert r.status_code == 404
    assert "NOT_A_REAL_EVENT_UID" in r.json()["detail"]


def test_lineage_does_not_trust_ocsf_extra_for_provenance(client: Any) -> None:
    """The `aletheia` block is rebuilt from the row, never read back out of the stored blob."""
    page = _events(client, limit=5)
    if not page["events"]:
        pytest.skip("aletheia.events is empty")
    for ev in page["events"]:
        lin = _lineage(client, ev["aletheia"]["event_uid"])
        block = lin["event"]["aletheia"]
        assert block["event_uid"] == lin["event_uid"]
        assert block["template_id"] == lin["template_id"]
        assert block["pack_version"] == lin["pack_version"]
        assert block["raw_sha256"].lower() == lin["raw_sha256"].lower()
